export const INDUSTRY_LIST: string[] = [
  'Administradoras de Fondos',
  'Aerolíneas',
  'Aeropuertos',
  'Agricultura',
  'Agroindustria',
  'Agua y Saneamiento',
  'Alimentos',
  'Auditoría',
  'Automotriz',
  'Bancos',
  'Bebidas',
  'Capacitación',
  'Carreteras',
  'Casinos',
  'Celulosa',
  'Centros Comerciales',
  'Centros Médicos',
  'Ciberseguridad',
  'Cloud Services',
  'Concesiones',
  'Construcción',
  'Consultoría',
  'Corredoras de Bolsa',
  'Corredoras Propiedades',
  'Courier',
  'Data Centers',
  'Distribución Eléctrica',
  'Distribución Mayorista',
  'E-Commerce',
  'Educación Escolar',
  'Educación Superior',
  'Energías Renovables',
  'Entretenimiento',
  'Factoring',
  'Farmacias',
  'Fintech',
  'Forestal',
  'Ganadería',
  'Gastronomía',
  'Generación Eléctrica',
  'Hotelería',
  'Ingeniería',
  'Inmobiliaria Desarrollo',
  'Inmobiliaria Renta',
  'Inteligencia Artificial',
  'Laboratorios',
  'Leasing',
  'Litio',
  'Logística',
  'Manufactura',
  'Marketing Digital',
  'Marketplace Digital',
  'Medios de Pago',
  'Minería Cobre',
  'Minería No Metálica',
  'Minería Oro',
  'Minería Plata',
  'Otras',
  'Packaging',
  'Pesca',
  'Petróleo y Gas',
  'Puertos',
  'Química',
  'Repuestos Automotrices',
  'Retail Especializado',
  'Retail Multitiendas',
  'Retail Supermercados',
  'Salmonicultura',
  'Salud Clínicas',
  'Seguros',
  'Servicios Industriales',
  'Servicios Profesionales',
  'Software SaaS',
  'Software Tradicional',
  'Talleres Automotrices',
  'Telecomunicaciones',
  'Textil',
  'Transmisión Eléctrica',
  'Transporte Ferroviario',
  'Transporte Marítimo',
  'Transporte Terrestre',
  'Turismo',
  'Utilities Eléctricas',
  'Viñas',
];
